### ISSUE TITLE
Create obs-prep_only layout

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#129]
Along the line of the other layouts, create a case that will stage the obs i.e. cycle without a model/da.
 something like this:

**obsprep_only.yaml**
``` yaml
suite: !Cycle
      <<: *suite_defaults

      obs_prep: !Task
        <<: *shared_task_template
        Trigger: !Depend  ( ~ suite.has_cycle('-24:00:00') | fcst_run.at('-24:00:00'))
        resources: !calc partition.resources.run_obs_prep
        config: [ base ]
        J_JOB: JJOB_OBS_PREP
...
```
Testing would have to be outside of the period where we have pre-stagged obs.
I suggested who should be doing this work, but feel free to re-assign (as long as you don't assign me :) ).
