### ISSUE TITLE
distance to coast filter

### ISSUE THREAD

**Issue by mjhossen** [NOAA-EMC/godas#281]
We apply a distance to coast filter to remove some observation near the coast. For 0.25 deg simulation we use 100km distance which is 3-4 grids from the coast. 

```
  - filter: Domain Check
    where:
    - variable: {name: distance_from_coast@GeoVaLs}
      minvalue: 100e3
```
