### ISSUE TITLE
Passivate <10C in sss_smap_jpl.yaml

### ISSUE THREAD

**Issue by liuxiao37k** [NOAA-EMC/godas#355]
The following filter to passivate high-lat sss obs is not present in sss_smap_jpl.yaml.

Please ignore and close the issue if this is intended.

```
  - filter: Domain Check
    action:
      name: passivate
    where:
    - variable: {name: sea_surface_temperature@GeoVaLs}
      minvalue: 10.0
```
