### ISSUE TITLE
Std Dev of the background error from a static ensemble: Part 1

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#446]
## Description
This is the uni-variate case of #445 . Forget about using cross-covariances between T/S and T/S/ssh. This means we would not be able to assimilate ADT. 

## Workflow steps and experiment setup

- [ ] Compute the std dev of the ensemble of perturbations, making sure they are remapped to the same vertical geometry. (@liuxiao37k )
- [ ] Prepare `var.yaml` (@liuxiao37k , @ShastriPaturi , @guillaumevernieres  )
- [ ] Update R2D2 with the new drifter obs (@ShastriPaturi , @mjhossen )

## Testing
JCSDA golden period

**Comment by liuxiao37k** [comment]
Initial discussion with @guillaumevernieres and @ShastriPaturi: to compute the std dev, first put together an [ensvariance.yml ](https://github.com/JCSDA-internal/soca/blob/develop/test/testinput/ensvariance.yml) and use the corresponding soca application to compute the variance, then convert to std dev by taking the sqrt of variance. Make sure to enable vertical remapping onto the same levels in the yaml.

**Comment by liuxiao37k** [comment]
A quick look at an example (20190401 restart, stddev after remapping, cpld forecasts 3 months out):
<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/213266060-be9d20d3-3ee2-4180-b6e8-4eea1e2b51e4.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/213266090-96775897-bfa8-4357-8790-060fb194dbf8.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/213266141-2a52cc86-25cc-403d-829c-f605306786cb.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/213266167-6e15bb4c-4dcc-41db-9fa7-d83868ff9593.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/2281138/213266181-8a3e1dca-4963-411f-b42d-58218e7d5026.png">

**Comment by guillaumevernieres** [comment]
> A quick look at an example (20190401 restart, stddev after remapping, cpld forecasts 3 months out): <img alt="image" width="468" src="https://user-images.githubusercontent.com/2281138/213266060-be9d20d3-3ee2-4180-b6e8-4eea1e2b51e4.png"> <img alt="image" width="468" src="https://user-images.githubusercontent.com/2281138/213266090-96775897-bfa8-4357-8790-060fb194dbf8.png"> <img alt="image" width="468" src="https://user-images.githubusercontent.com/2281138/213266141-2a52cc86-25cc-403d-829c-f605306786cb.png"> <img alt="image" width="468" src="https://user-images.githubusercontent.com/2281138/213266167-6e15bb4c-4dcc-41db-9fa7-d83868ff9593.png"> <img alt="image" width="468" src="https://user-images.githubusercontent.com/2281138/213266181-8a3e1dca-4963-411f-b42d-58218e7d5026.png">

Thanks @liuxiao37k .
We need to start plotting cross sections, I was looking at the file you pointed us to yesterday and some of the section had "weird looking features". We have scripts somewhere to plot that stuff ...

**Comment by liuxiao37k** [comment]
@guillaumevernieres Sure. Does the script take care of the remapping of each vertical column onto the same depth intervals?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Sure. Does the script take care of the remapping of each vertical column onto the same depth intervals?

no, it just plots a cross section of a field given the field and layer thicknesses.

**Comment by liuxiao37k** [comment]
> > @guillaumevernieres Sure. Does the script take care of the remapping of each vertical column onto the same depth intervals?
> 
> no, it just plots a cross section of a field given the field and layer thicknesses.

@guillaumevernieres but for restart files, each column has different thicknesses (h is a 3d matrix). Wouldn't that be an issue for plotting cross sections, especially in the shallower waters?

**Comment by guillaumevernieres** [comment]
the scripts reads the thickness to plot the field at the proper depth and plots things like this:
![image](https://user-images.githubusercontent.com/14031856/213482147-a515f4e1-7838-4827-b8db-d28664882c1c.png)

This is just an example and not from the file you pointed us to.

**Comment by liuxiao37k** [comment]
@guillaumevernieres cool. thanks. that's what I asked about. if you get a chance to find the scripts, please let me know.

**Comment by guillaumevernieres** [comment]
We created a repo with @kbhargava a while back. She's been maintaining it and I think that feature still works:
https://github.com/JCSDA-internal/soca-diagnostics
... you could also ask chatgpt to write you a plotting script :)

**Comment by kbhargava** [comment]
> We created a repo with @kbhargava a while back. She's been maintaining it and I think that feature still works: https://github.com/JCSDA-internal/soca-diagnostics ... you could also ask chatgpt to write you a plotting script :)

Last I checked  it was working fine with the develop branch. @liuxiao37k let me know if you have any issues, I will update the code.

**Comment by liuxiao37k** [comment]
@kbhargava Thanks, Kriti. I ended up putting together a few lines in matlab and looks like it was able to replicate what the python scripts do. I'll give a try of what's in the repo and let you know. 
@guillaumevernieres here are a few examples (T and S at lat=0 and lat=30), using the stddev calculated from the ensemble forecasts. I'll plot more and upload them to google drive.
I am not sure what those "hot spots" are ~350-450m. Need to take a closer look. Californian undercurrent?
<img width="440" alt="image" src="https://user-images.githubusercontent.com/2281138/213753057-e4cfaf1c-2798-4cd5-a575-7bf8a596b891.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/2281138/213753133-1b6bbd91-b502-47a9-9e20-60944dae118d.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/2281138/213753188-300f694e-1bcb-498b-a99f-5c7a682c4d1d.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/2281138/213753203-1f92f947-129d-48ee-9b61-dc2e081f868b.png">

**Comment by guillaumevernieres** [comment]
Nice! Thanks @liuxiao37k .
Let's ask (nicely?) @ShastriPaturi to run a single cycle for the test case he put together in issue #415 with your std-dev files and see what happens ... We'll "crank-up" the variance to make sure we emphasize possible issues.

**Comment by guillaumevernieres** [comment]
@ShastriPaturi , can you try this:
```yaml
  background error:

    covariance model: SABER

    saber central block:
      saber block name: ID
      active variables: *soca_vars

    saber outer blocks:
    - saber block name: StdDev
      input fields:
      - parameter: StdDev
        file:
          read_from_file: 1
          basename: ./
          remap_filename: ./bkg/MOM.res.nc
          ocn_filename: ocn.bkgerr_stddev.nc
          ice_filename: ice.bkgerr_stddev.nc
          date: *bkg_date

    linear variable change:
      input variables: *soca_vars
      output variables: *soca_vars
      linear variable changes:

      - linear variable change name: VertConvSOCA
        Lz_min: 0.0
        Lz_mld: 0
        Lz_mld_max: 1.0
        scale_layer_thick: 5

      - linear variable change name: HorizFiltSOCA
        niter: 4
        filter variables: *soca_vars
```
