### ISSUE TITLE
Identify possible issues in VertConv

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#483]
Configure the `var.yaml` so the B-matrix would look something like 
$\bf B = C_v C_h C_v^{T}$ 

and the corresponding `yaml` snippet 

```yaml
  background error:
    covariance model: SocaError
       [...]
    linear variable change:
      input variables: *soca_vars
      output variables: *soca_vars
      linear variable changes:

      - linear variable change name: VertConvSOCA
        Lz_min: 0.0
        Lz_mld: 0
        Lz_mld_max: 1.0
        scale_layer_thick: 5
```

run the var application to generate an increment and look for issues in the increment.
